export { default as MantineAnchor } from './Anchor/component'
export { default as MantineBreadcrumbs } from './Breadcrumbs/component'
export { default as MantineBurger } from './Burger/component'
export { default as MantineNavLink } from './NavLink/component'
export { default as MantinePagination } from './Pagination/component'
export { default as MantineStepper } from './Stepper/component'
export { default as MantineTabs } from './Tabs/component'

export { default as MantineAnchorMeta } from './Anchor/metadata'
export { default as MantineBreadcrumbsMeta } from './Breadcrumbs/metadata'
export { default as MantineBurgerMeta } from './Burger/metadata'
export { default as MantineNavLinkMeta } from './NavLink/metadata'
export { default as MantinePaginationMeta } from './Pagination/metadata'
export { default as MantineStepperMeta } from './Stepper/metadata'
export { default as MantineTabsMeta } from './Tabs/metadata'
