import {
    MantineActionIconMeta,
    MantineButtonMeta,
    MantineCloseButtonMeta,
    MantineCopyButtonMeta,
    MantineFileButtonMeta,
    MantineUnstyledButtonMeta,
} from './Buttons'
import {
    MantineAccordionMeta,
    MantineAvatarMeta,
    MantineBackgroundImageMeta,
    MantineBadgeMeta,
    MantineCardMeta,
    MantineColorSwatchMeta,
    MantineImageMeta,
    MantineIndicatorMeta,
    MantineKbdMeta,
    MantineSpoilerMeta,
    MantineThemeIconMeta,
    MantineTimelineMeta,
} from './DataDisplay'
import {
    MantineAlertMeta,
    MantineLoaderMeta,
    MantineNotificationMeta,
    MantineProgressMeta,
    MantineRingProgressMeta,
    MantineSkeletonMeta,
} from './Feedback'
import {
    MantineAutocompleteMeta,
    MantineCheckboxMeta,
    MantineChipMeta,
    MantineColorInputMeta,
    MantineColorPickerMeta,
    MantineFileInputMeta,
    MantineInputMeta,
    MantineJsonInputMeta,
    MantineMultiSelectMeta,
    MantineNativeSelectMeta,
    MantineNumberInputMeta,
    MantinePasswordInputMeta,
    MantinePinInputMeta,
    MantineRadioMeta,
    MantineRatingMeta,
    MantineSegmentedControlMeta,
    MantineSelectMeta,
    MantineSliderMeta,
    MantineSwitchMeta,
    MantineTextareaMeta,
    MantineTextInputMeta,
    MantineTransferListMeta,
} from './Inputs'
import {
    MantineAppShellMeta,
    MantineAspectRatioMeta,
    MantineCenterMeta,
    MantineContainerMeta,
    MantineFlexMeta,
    MantineGridMeta,
    MantineGroupMeta,
    MantineMediaQueryMeta,
    MantineSimpleGridMeta,
    MantineSpaceMeta,
    MantineStackMeta,
} from './Layout'
import {
    MantineBoxMeta,
    MantineCollapseMeta,
    MantineDividerMeta,
    MantineFocusTrapMeta,
    MantinePaperMeta,
    MantinePortalMeta,
    MantineScrollAreaMeta,
    MantineTransitionMeta,
} from './Misc'
import {
    MantineAnchorMeta,
    MantineBreadcrumbsMeta,
    MantineBurgerMeta,
    MantineNavLinkMeta,
    MantinePaginationMeta,
    MantineStepperMeta,
    MantineTabsMeta,
} from './Navigation'
import {
    MantineCalendarMeta,
    MantineCarouselMeta,
    MantineDateInputMeta,
    MantineDatePickerInputMeta,
    MantineDatePickerMeta,
    MantineDatesProviderMeta,
    MantineDateTimePickerMeta,
    // MantineDropzoneMeta,
    MantineModalsProviderMeta,
    MantineMonthPickerInputMeta,
    MantineMonthPickerMeta,
    MantineNavigationProgressMeta,
    MantineNotificationsMeta,
    MantinePrismMeta,
    MantineRichTextEditorMeta,
    MantineSpotlightProviderMeta,
    MantineTimeInputMeta,
    MantineYearPickerInputMeta,
    MantineYearPickerMeta,
} from './Others'
import {
    MantineAffixMeta,
    MantineDialogMeta,
    MantineDrawerMeta,
    MantineHoverCardMeta,
    MantineLoadingOverlayMeta,
    MantineMenuMeta,
    MantineModalMeta,
    MantineOverlayMeta,
    MantinePopoverMeta,
    MantineTooltipMeta,
} from './Overlay'
import {
    MantineBlockquoteMeta,
    MantineCodeMeta,
    MantineHighlightMeta,
    MantineListMeta,
    MantineMarkMeta,
    MantineTableMeta,
    MantineTextMeta,
    MantineTitleMeta,
    MantineTypographyStylesProviderMeta,
} from './Typography'

export const AtomicMetadata = [
    ...MantineAccordionMeta,
    ...MantineAvatarMeta,
    ...MantineBackgroundImageMeta,
    ...MantineBadgeMeta,
    ...MantineCardMeta,
    ...MantineColorSwatchMeta,
    ...MantineImageMeta,
    ...MantineIndicatorMeta,
    ...MantineKbdMeta,
    ...MantineSpoilerMeta,
    ...MantineThemeIconMeta,
    ...MantineTimelineMeta,
    ...MantineActionIconMeta,
    ...MantineButtonMeta,
    ...MantineCloseButtonMeta,
    ...MantineCopyButtonMeta,
    ...MantineFileButtonMeta,
    ...MantineUnstyledButtonMeta,
    ...MantineAffixMeta,
    ...MantineDialogMeta,
    ...MantineDrawerMeta,
    ...MantineHoverCardMeta,
    ...MantineLoadingOverlayMeta,
    ...MantineMenuMeta,
    ...MantineModalMeta,
    ...MantineOverlayMeta,
    ...MantinePopoverMeta,
    ...MantineTooltipMeta,
    ...MantineAlertMeta,
    ...MantineLoaderMeta,
    ...MantineNotificationMeta,
    ...MantineProgressMeta,
    ...MantineRingProgressMeta,
    ...MantineSkeletonMeta,
    ...MantineAnchorMeta,
    ...MantineBreadcrumbsMeta,
    ...MantineBurgerMeta,
    ...MantineNavLinkMeta,
    ...MantinePaginationMeta,
    ...MantineStepperMeta,
    ...MantineTabsMeta,
    ...MantineAppShellMeta,
    ...MantineAspectRatioMeta,
    ...MantineCenterMeta,
    ...MantineContainerMeta,
    ...MantineFlexMeta,
    ...MantineGridMeta,
    ...MantineGroupMeta,
    ...MantineMediaQueryMeta,
    ...MantineSimpleGridMeta,
    ...MantineSpaceMeta,
    ...MantineStackMeta,
    ...MantineAutocompleteMeta,
    ...MantineCheckboxMeta,
    ...MantineChipMeta,
    ...MantineColorInputMeta,
    ...MantineColorPickerMeta,
    ...MantineFileInputMeta,
    ...MantineInputMeta,
    ...MantineJsonInputMeta,
    ...MantineMultiSelectMeta,
    ...MantineNativeSelectMeta,
    ...MantineNumberInputMeta,
    ...MantinePasswordInputMeta,
    ...MantinePinInputMeta,
    ...MantineRadioMeta,
    ...MantineRatingMeta,
    ...MantineSegmentedControlMeta,
    ...MantineSelectMeta,
    ...MantineSliderMeta,
    ...MantineSwitchMeta,
    ...MantineTextInputMeta,
    ...MantineTextareaMeta,
    ...MantineTransferListMeta,
    ...MantineBlockquoteMeta,
    ...MantineCodeMeta,
    ...MantineHighlightMeta,
    ...MantineListMeta,
    ...MantineMarkMeta,
    ...MantineTableMeta,
    ...MantineTextMeta,
    ...MantineTitleMeta,
    ...MantineTypographyStylesProviderMeta,
    ...MantineBoxMeta,
    ...MantineCollapseMeta,
    ...MantineDividerMeta,
    ...MantineFocusTrapMeta,
    ...MantinePaperMeta,
    ...MantinePortalMeta,
    ...MantineScrollAreaMeta,
    ...MantineTransitionMeta,
    ...MantineCalendarMeta,
    ...MantineDateInputMeta,
    ...MantineDatePickerMeta,
    ...MantineDatePickerInputMeta,
    ...MantineDateTimePickerMeta,
    ...MantineDatesProviderMeta,
    ...MantineMonthPickerMeta,
    ...MantineMonthPickerInputMeta,
    ...MantineTimeInputMeta,
    ...MantineYearPickerMeta,
    ...MantineYearPickerInputMeta,
    ...MantineCarouselMeta,
    // ...MantineDropzoneMeta,
    ...MantineModalsProviderMeta,
    ...MantineNotificationsMeta,
    ...MantineNavigationProgressMeta,
    ...MantinePrismMeta,
    ...MantineSpotlightProviderMeta,
    ...MantineRichTextEditorMeta,
]
