export { default as MantineBox } from './Box/component'
export { default as MantineCollapse } from './Collapse/component'
export { default as MantineDivider } from './Divider/component'
export { default as MantineFocusTrap } from './FocusTrap/component'
export { default as MantinePaper } from './Paper/component'
export { default as MantinePortal } from './Portal/component'
export { default as MantineScrollArea } from './ScrollArea/component'
export { default as MantineTransition } from './Transition/component'

export { default as MantineBoxMeta } from './Box/metadata'
export { default as MantineCollapseMeta } from './Collapse/metadata'
export { default as MantineDividerMeta } from './Divider/metadata'
export { default as MantineFocusTrapMeta } from './FocusTrap/metadata'
export { default as MantinePaperMeta } from './Paper/metadata'
export { default as MantinePortalMeta } from './Portal/metadata'
export { default as MantineScrollAreaMeta } from './ScrollArea/metadata'
export { default as MantineTransitionMeta } from './Transition/metadata'
